### ISSUE TITLE
YT poster image urls cause insecure connection warnings in Firefox because they are using http instead of https

### ISSUE THREAD

**Issue by moodleacademy** [justinhunt/moodle-filter_videoeasy#6]
YouTube poster image urls should be using https now.
Firefox complains that there are insecure links to images because the filter uses http to build these urls.
These should now be https. 

The http links redirect to https anyway but it would be good to have https links by default.

(Chrome and Edge do not complain about this.)

**Comment by justinhunt** [comment]
Fixed in https://github.com/justinhunt/moodle-filter_videoeasy/commit/f23e7bd4dfeca2bc3d7bd150498d2111c606a371
Thanks for the pull request, but I'm sorry I missed it and made a few other changes too.
I created a new version of the youtube lightbox template that uses a different lightbox (fancybox) which works a bit better, and does more out of the box,  and is not shimmed etc. Please try it. (on the list of templates, click "update" beside the template).

If you have made changes of your own to the youtubelightbox template, rename it to something like ma-youtubelightbox so you still have it. Then create a new template from the youtubelightbox preset.
